### ISSUE TITLE
Who will be maintainer?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework2G2#1]
Hi All,

Who will be maintainer on this project? I was maintainer for my last group so I probably shouldn't do it again

**Comment by pratibha77118** [comment]
I wasn't the maintainer on last group but I don't have much idea on this. I think I will need help on this.

**Comment by pratibha77118** [comment]
Is is true the maintainer in former group shouldn't be maintainer here?

**Comment by WildJimmy** [comment]
I think so. The professor wants everyone to have experience as a maintainer from the sounds of it

**Comment by Pranjal-Srivastava-2023** [comment]
@pratibha77118 I guess you will be the maintainer for this group. I was the maintainer last time.
