### ISSUE TITLE
Group 2 will go with axis array summation

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework2G2#11]
Hi @WildJimmy & @Pranjal-Srivastava-2023 
We group are going with axis array summation as all other simpler operation are already taken by other groups.
If you find any other simpler operation left chosen by other group, inform me. We should be deciding this soon.

**Comment by Pranjal-Srivastava-2023** [comment]
@pratibha77118 Yes, we can go with Array axis summations.

**Comment by pratibha77118** [comment]
Okay then I will be informing other group about this.
