### ISSUE TITLE
Merge arrray axis summation codes.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework2G2#19]
@pratibha77118 accept my merge request. I have added two codes for array axis summation:
1. Without using numpy
2. Using numpy
You can now run the unit tests.

**Comment by pratibha77118** [comment]
@Pranjal-Srivastava-2023 
We are supposed to find the execution time for this operation. Aren't we?

**Comment by Pranjal-Srivastava-2023** [comment]
Yes, that is not a problem. It is just one line of code. I will improve the code and send more merge requests. Meanwhile, you can do the unit test.

**Comment by pratibha77118** [comment]
I did the unit test. It works for any array. Please include Einstein notation also in your new code.
