### ISSUE TITLE
What will our roles be?

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework2G2#2]
Hi All,

What will our roles be on the project? Last time I made the algorithm so I should probably do the unit test or documentation (I would prefer documentation honestly)

**Comment by pratibha77118** [comment]
I did algorithm part earlier. So I will go with unit test.

**Comment by Pranjal-Srivastava-2023** [comment]
@WildJimmy @pratibha77118 I will do the algorithm part.
