### ISSUE TITLE
Milestone created

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework2G2#22]
Hi @Pranjal-Srivastava-2023 @WildJimmy,
I have created the milestone to track our work. I ,however, is confused on updating it. Please assist me on this.

**Comment by Pranjal-Srivastava-2023** [comment]
@pratibha77118 when you select the milestone and create issues inside it, they are tracked. Once you close these issues, you make progress. If all the issues in the milestone get closed then the milestone is achieved. I have added three issues in our milestone, so only close them once they are 100% resolved.

You can add more HW related tasks as issues directly in the milestone.

**Comment by pratibha77118** [comment]
Got it. Thanks for your suggestion.
