### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by Pranjal-Srivastava-2023** [ubsuny/23-Homework2G2#25]
This will almost be the final task to achieve the milestone.

**Comment by Pranjal-Srivastava-2023** [comment]
Providing algorithms for @WildJimmy to include in the documentation.

**Comment by Pranjal-Srivastava-2023** [comment]
# Array Axis Summation (Without Numpy)

## Introduction

This code demonstrates how to perform array axis summation without using NumPy. It calculates the sum along rows (axis 0) and columns (axis 1) of a 2D list using the Einstein summation convention. The code also measures and reports the execution time in microseconds for the array summation operation.

## Algorithm

### Input:
- `array`: A 2D list representing the input array for which summations are to be calculated.

### Output:
- Prints the original array.
- Calculates and prints the sum along rows (axis 0) and columns (axis 1) using the Einstein summation convention.
- Prints the elapsed time in microseconds for the array summation operation.

### Steps:

1. Define a function `sum_rows(arr)` that takes a 2D list `arr` as input.
   - Initialize an empty list `row_sums`.
   - For each row `row` in `arr`, calculate the sum of elements in `row` using the `sum()` function.
   - Append each row's sum to the `row_sums` list.
   - Return `row_sums`.

2. Define a function `sum_columns(arr)` that takes a 2D list `arr` as input.
   - Initialize an empty list `column_sums`.
   - Determine the number of columns `num_columns` in `arr` (length of any row in `arr`).
   - For each column index `j` from 0 to `num_columns - 1`:
     - Initialize a variable `column_sum` to 0.
     - For each row `row` in `arr`, add the element `arr[i][j]` to `column_sum`.
     - Append `column_sum` to the `column_sums` list.
   - Return `column_sums`.

3. Calculate row sums and column sums by calling the `sum_rows` and `sum_columns` functions on the input `array`.

4. Print the original 2D list `array`.
   - For each row `row` in `array`, print `row`.

5. Print the computed row sums using Einstein summation.
   - Use the `np.einsum()` function with the string `'ij->j'` to calculate the sum along rows (axis 0) using Einstein summation.
   - Print the result.

6. Print the computed column sums using Einstein summation.
   - Use the `np.einsum()` function with the string `'ij->i'` to calculate the sum along columns (axis 1) using Einstein summation.
   - Print the result.

7. Measure the execution time of the entire array summation operation:
   - Initialize a variable `start_time` to the current time in microseconds.
   - Execute the array summation operation.
   - Initialize a variable `end_time` to the current time in microseconds.
   - Calculate the elapsed time as `elapsed_time = end_time - start_time`.

8. Print the elapsed time in microseconds for the array summation operation.

## Usage

To use this code, simply provide a 2D list `array` as input to the `array_axis_summation` function. The code will perform array axis summation, print the results, and report the execution time.

```python
user_array = [[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]
array_axis_summation(user_array)

**Comment by Pranjal-Srivastava-2023** [comment]
# Array Axis Summation (Using NumPy)

## Introduction

This code demonstrates how to perform array axis summation using NumPy and the Einstein summation convention. It calculates the sum along rows (axis 0) and columns (axis 1) of a 2D NumPy array and prints the original array and the summation results. Additionally, the code measures and reports the execution time in microseconds for the array summation operation.

## Algorithm

### Input:
- `array`: A 2D NumPy array representing the input array for which summations are to be calculated.

### Output:
- Prints the original array.
- Calculates and prints the sum along rows (axis 0) and columns (axis 1) using the Einstein summation convention.
- Prints the elapsed time in microseconds for the array summation operation.

### Steps:

1. Calculate row sums and column sums using NumPy and the Einstein summation convention:
   - Use the `np.einsum()` function to calculate the sum along rows (axis 0) with the string `'ij->j'`.
   - Store the result in `row_sums`.
   - Use the `np.einsum()` function to calculate the sum along columns (axis 1) with the string `'ij->i'`.
   - Store the result in `column_sums`.

2. Print the original 2D NumPy array `array`.
   - Use `print()` to display the content of `array`.

3. Print the computed row sums using Einstein summation.
   - Use `print()` to display the content of `row_sums`.

4. Print the computed column sums using Einstein summation.
   - Use `print()` to display the content of `column_sums`.

5. Measure the execution time of the entire array summation operation:
   - Define a function `timed_code()` that creates a sample 2D NumPy array `user_array`.
   - Call the `array_axis_summation` function with `user_array` as input.
   - Initialize a variable `start_time` to the current time in microseconds.
   - Execute the `timed_code` function.
   - Initialize a variable `end_time` to the current time in microseconds.
   - Calculate the elapsed time as `elapsed_time = end_time - start_time`.

6. Print the elapsed time in microseconds for the array summation operation.

## Usage

To use this code, simply provide a 2D NumPy array `array` as input to the `array_axis_summation` function. The code will perform array axis summation, print the results, and report the execution time.

```python
import numpy as np

user_array = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
array_axis_summation(user_array)

**Comment by WildJimmy** [comment]
@Pranjal-Srivastava-2023 Thank you very much for the detailed explanations. I have incorporated this into my documentation on the algorithms and will be pushing a merge request soon
