### ISSUE TITLE
Can you add functions to calculate the execution time after and before this line? 

### ISSUE THREAD

**Issue by Mosaddeq107** [ubsuny/23-Homework2G2#29]
Since your algorithms don't measure the execution time, you can add some functions after or before this line: 

https://github.com/ubsuny/23-Homework2G2/blob/4f2e6bd81a2deb5a59978412fa7ac8d923e5e8c3/array_axis_summation.py#L22

**Comment by pratibha77118** [comment]
Yes @Mosaddeq107,
We have to use loops to implement Einstein notation in our code. Thanks for suggesting.
