### ISSUE TITLE
Documentation reference

### ISSUE THREAD

**Issue by poojashresthacode** [ubsuny/23-Homework2G2#34]
Hy, so while writing documemtation, where are we supposed to place the references? Should we place it at last or should we put it in the the exact place where it is used?

**Comment by s4il3sh** [comment]
We have placed it at the last part of the documentation. I also would like to know what other groups are doing about it.

**Comment by WildJimmy** [comment]
This is a great question. I placed mine at the end in their own section, but if it's more formal I may figure out how to add them as footnotes to properly reference the place in which they're used
