### ISSUE TITLE
Conversation in the other groups

### ISSUE THREAD

**Issue by uarif** [ubsuny/23-Homework2G2#37]
Hi, 
We have to make the certain number of conversations in the other groups too. I don't see any option in the other group to make one. How are you guys doing it?
Thanks.

**Comment by s4il3sh** [comment]
@uarif just go to the issue and comment on the other group. That's how you do conversation.

**Comment by AhmedCode99** [comment]
@s4il3sh thanks

**Comment by pratibha77118** [comment]
Yes the same.
