### ISSUE TITLE
Compairing time execution

### ISSUE THREAD

**Issue by pratibha77118** [ubsuny/23-Homework2G2#38]
Hi @Pranjal-Srivastava-2023,
 The code works perfectly fine except that the sum for rows and columns are alternating. I fixed it by changing i and j .
However, I could not understand why the matrix with 4 rows and 4 columns have smaller execution time than the one with 3 rows and 3 columns with smaller value of arrays.

**Comment by pratibha77118** [comment]
Also, elapsed_time = timeit.timeit(timed_code, number=1) what does "number=1" signify? Does it has any role for the issue I got here?

**Comment by Pranjal-Srivastava-2023** [comment]
@pratibha77118 The number parameter in the timeit.timeit function specifies the number of times the given code should be executed when measuring its execution time. Maybe when you run the code multiple times by changing number=10 (for example) you might get a different answer for 4X4 matrix.

**Comment by AhmedCode99** [comment]
Interesting. do you have any useful references related to timeit.time.it?

**Comment by WildJimmy** [comment]
@AhmedCode99 you can read the documentation for timeit here:
https://docs.python.org/3/library/timeit.html
