### ISSUE TITLE
Documentation Added and (Hopefully) Finalized

### ISSUE THREAD

**Issue by WildJimmy** [ubsuny/23-Homework2G2#43]
Hi all,

I've just made the merge request to add my documentation markdown file to the main branch. I was going to add the docstrings as well, but noticed that they're already present in the python file. I think it's finished, but if you have any last-second feedback please let me know. I will likely look it over again tomorrow morning to make sure there's no egregious errors.

**Comment by pratibha77118** [comment]
Hi @WildJimmy 
I got the result where elapsed time for algorithm using numpy is greater than the manually written algorithm. Isn't this against the result you noted in documentation?

**Comment by WildJimmy** [comment]
Hi @pratibha77118 
It depends on where you run it, as well as the size of the array (I'll revise this and make a note of it). That said, the larger the array is, the faster einsum is compared to not using numpy. See the attached screenshots for me running the code locally. The first line is the size of the arrays I'm using which I just made with np.random.rand(*array size*). Your mileage may vary based on the environment, but I'm pretty sure the relative result will be the same

![image](https://github.com/ubsuny/23-Homework2G2/assets/94491866/f118e6cd-4f34-4345-8e0e-adefa9d99829)

**Comment by pratibha77118** [comment]
Thanks. I get it.
